export const tag = [
  { value: "software", label: "Software Development" },
  { value: "teacher", label: "Teaching" },
  { value: "plumber", label: "Plumber" },
  { value: "carpenter", label: "Carpenter" },
  { value: "helper", label: "Helper" },
  { value: "electrician", label: "Electrician" },
  { value: "mechanic", label: "Mechanic" },
  { value: "doctor", label: "Doctor" },
  { value: "nurse", label: "Nurse" },
  { value: "driver", label: "Driver" },
  { value: "chef", label: "Chef" },
  { value: "bartender", label: "Bartender" },
  { value: "waiter", label: "Waiter/Waitress" },
  { value: "accountant", label: "Accountant" },
  { value: "architect", label: "Architect" },
  { value: "designer", label: "Graphic Designer" },
  { value: "webdeveloper", label: "Web Developer" },
  { value: "contentwriter", label: "Content Writer" },
  { value: "marketing", label: "Marketing Specialist" },
  { value: "sales", label: "Sales Representative" },
  { value: "photographer", label: "Photographer" },
  { value: "videographer", label: "Videographer" },
  { value: "consultant", label: "Business Consultant" },
  { value: "analyst", label: "Data Analyst" },
  { value: "security", label: "Security Guard" },
  { value: "painter", label: "Painter" },
  { value: "tailor", label: "Tailor" },
  { value: "hairdresser", label: "Hairdresser" },
  { value: "makeupartist", label: "Makeup Artist" },
  { value: "trainer", label: "Fitness Trainer" },
  { value: "coach", label: "Sports Coach" },
  { value: "scientist", label: "Scientist" },
  { value: "researcher", label: "Researcher" },
  { value: "pilot", label: "Pilot" },
  { value: "translator", label: "Translator" },
  { value: "interpreter", label: "Interpreter" },
  { value: "engineer", label: "Civil Engineer" },
  { value: "mechanicalengineer", label: "Mechanical Engineer" },
  { value: "technician", label: "Technician" },
  { value: "socialworker", label: "Social Worker" },
  { value: "lawyer", label: "Lawyer" },
  { value: "paralegal", label: "Paralegal" },
  { value: "journalist", label: "Journalist" },
  { value: "editor", label: "Editor" },
  { value: "eventplanner", label: "Event Planner" },
  { value: "realestate", label: "Real Estate Agent" },
  { value: "librarian", label: "Librarian" },
  { value: "gardener", label: "Gardener" },
  { value: "farmer", label: "Farmer" },
  { value: "veterinarian", label: "Veterinarian" },
  { value: "psychologist", label: "Psychologist" },
  { value: "artist", label: "Artist" },
];
